import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { ModelProfile } from "../model-profile.js";
import { applyMcpToolNameRule } from "../../mcp/mcp-grammar-builder.js";

function resolveDefaultGrammarsDir(): string {
  const nextToBinary = join(dirname(process.execPath), "grammars");
  if (existsSync(nextToBinary)) {
    return nextToBinary;
  }
  const here = dirname(fileURLToPath(import.meta.url));
  return resolve(here, "../../../grammars");
}

export interface BuildGrammarOptions {
  /**
   * Optional pre-built `mcp-server-tool ::= ...` line. Generated by
   * `buildMcpToolNameRule(McpManager.listAllToolMeta())` after every
   * connect / disconnect. When `null` / omitted, the static
   * permissive placeholder in `tool-call.gbnf` survives — so a
   * grammar rebuild only invalidates the KV cache when the dynamic
   * list of MCP tool names actually changed.
   */
  mcpToolNameRule?: string | null;
}

export async function buildGrammar(
  profile: ModelProfile,
  grammarsDir = resolveDefaultGrammarsDir(),
  options: BuildGrammarOptions = {},
): Promise<string> {
  const baseGrammar = await readFile(join(grammarsDir, "tool-call.gbnf"), "utf8");
  const withMcp = applyMcpToolNameRule(baseGrammar, options.mcpToolNameRule ?? null);
  if (!profile.allowThinkPrelude || profile.reasoningStyle === "none") return withMcp;
  const ruleStem = profile.id === "gemma4-think" ? "channel" : "think";
  // After thinking, the model emits the array-only form (always `[`).
  // This avoids the GBNF first-token bias toward `{` that small models
  // exhibit even when their `<think>` block reasoned about parallelism.
  const rootRule = `root ::= ${ruleStem}-prelude tool-call-array`;
  const withPreludeRoot = withMcp.replace(/^root ::= .*$/m, rootRule);
  const preludeRules = buildUntilSentinelRules(ruleStem, profile.reasoningCloseTag);
  return `${withPreludeRoot.trimEnd()}\n${preludeRules}\n`;
}

function buildUntilSentinelRules(ruleStem: string, sentinel: string): string {
  const preludeRule = `${ruleStem}-prelude`;
  const bodyRule = `${ruleStem}-body`;
  const fragmentRule = `${ruleStem}-fragment`;
  const fragments = [`[^${escapeCharClass(sentinel[0]!)}]+`];

  for (let idx = 0; idx < sentinel.length - 1; idx += 1) {
    const prefix = sentinel.slice(0, idx + 1);
    const nextChar = sentinel[idx + 1]!;
    fragments.push(`${quoteGbnf(prefix)} [^${escapeCharClass(nextChar)}]`);
  }

  // Bounded trailing whitespace between the reasoning-close sentinel and
  // the start of `tool-call-array` (`[`). The global `ws` rule is
  // unbounded (`[ \t\n\r]*`) which is fine inside JSON but on this seam
  // it lets small reasoning-capable models (e.g. Gemma 4 26B-A4B) slide
  // into a whitespace-only degenerate loop after a long `<think>` /
  // `<|channel>thought` block: the sampler keeps emitting newlines until
  // `max_tokens` instead of converging on the `[`. Eight characters is
  // enough for any natural " " / "\n" / "  " gap and short enough to
  // bound the failure mode.
  return [
    `${preludeRule} ::= ${bodyRule} ${quoteGbnf(sentinel)} prelude-trail-ws`,
    `${bodyRule} ::= ${fragmentRule}*`,
    `${fragmentRule} ::= ${fragments.join(" | ")}`,
    `prelude-trail-ws ::= ( [ \\t\\n\\r] ){0,8}`,
  ].join("\n");
}

function quoteGbnf(text: string): string {
  return `"${text
    .replace(/\\/g, "\\\\")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")
    .replace(/"/g, '\\"')}"`;
}

function escapeCharClass(char: string): string {
  return char.replace(/\\/g, "\\\\").replace(/]/g, "\\]").replace(/-/g, "\\-");
}
