export { StdioProtocol, framed } from "./stdio-protocol.js";
export type {
  RequestHandler,
  StdioProtocolOptions,
} from "./stdio-protocol.js";
export { MessageRouter } from "./message-router.js";
export type { RouteHandler } from "./message-router.js";
export { SessionPool } from "./session-pool.js";
export type { SessionPoolEntry } from "./session-pool.js";
export { createAgentEventForwarder } from "./event-forwarder.js";

export {
  PROTOCOL_VERSION,
  isHostRequest,
  isSidecarEvent,
  isSidecarResponse,
} from "./protocol/index.js";
export type {
  RequestType,
  EventType,
  SidecarError,
  HostRequest,
  SidecarResponse,
  SidecarEvent,
  SidecarMessage,
  SessionSummary,
  SessionCreatePayload,
  SessionCreateResult,
  SessionListPayload,
  SessionListResult,
  SessionGetPayload,
  SessionGetResult,
  SessionOpenPayload,
  SessionOpenResult,
  SessionDeletePayload,
  SessionDeleteResult,
  ChatSendPayload,
  ChatSendResult,
  ChatCancelPayload,
  ChatCancelResult,
  ApprovalResolvePayload,
  ApprovalResolveResult,
  PingResult,
  ShutdownResult,
  TaskCreatePayload,
  TaskCreateResult,
  TaskListPayload,
  TaskListResult,
  TaskGetPayload,
  TaskGetResult,
  TaskCancelPayload,
  TaskCancelResult,
  TaskRunPayload,
  TaskRunResult,
  TaskDrainPayload,
  TaskDrainResult,
  SessionCreatedPayload,
  SessionOpenedPayload,
  SessionDeletedPayload,
  TurnStartedPayload,
  TurnFinishedPayload,
  StepStartedPayload,
  StepFinishedPayload,
  LoopDetectedPayload,
  SessionCompletedPayload,
  SessionFailedPayload,
  UserMessagePayload,
  AssistantReplyPayload,
  AssistantDeltaPayload,
  ReasoningDeltaPayload,
  ReasoningPayload,
  ToolCallStartedPayload,
  ToolCallResultPayload,
  ToolAutoloadedPayload,
  PromptCapturedPayload,
  ParseRetryPayload,
  BatchTrimmedPayload,
  ApprovalRequestPayload,
  ChannelStatusPayload,
  SkillRegistryUpdatedPayload,
  TaskUpdatedPayload,
  McpStatusPayload,
  LlmUnavailablePayload,
  LogPayload,
  MetricPayload,
  ErrorPayload,
  // memory.* (phase 5)
  MemoryProfileListPayload,
  MemoryProfileListResult,
  MemoryProfileHistoryPayload,
  MemoryProfileHistoryResult,
  MemoryNotesRecallPayload,
  MemoryNotesRecallResult,
  MemoryNotesListPayload,
  MemoryNotesListResult,
  MemoryNotesGetPayload,
  MemoryNotesGetResult,
  MemoryLessonsListPayload,
  MemoryLessonsListResult,
  MemoryLessonsGetPayload,
  MemoryLessonsGetResult,
  MemoryProceduresListPayload,
  MemoryProceduresListResult,
  MemoryProceduresGetPayload,
  MemoryProceduresGetResult,
  MemoryLinksListPayload,
  MemoryLinksListResult,
  MemoryLinksExpandPayload,
  MemoryLinksExpandResult,
  MemoryVotesListPayload,
  MemoryVotesListResult,
  // mcp.* (phase 6)
  McpListPayload,
  McpListResult,
  McpAddPayload,
  McpAddResult,
  McpRemovePayload,
  McpRemoveResult,
  McpRefreshPayload,
  McpRefreshResult,
  // skill.* (phase 7)
  SkillListPayload,
  SkillListResult,
  SkillEnablePayload,
  SkillEnableResult,
  SkillDisablePayload,
  SkillDisableResult,
  SkillInstallPayload,
  SkillInstallResult,
  SkillUninstallPayload,
  SkillUninstallResult,
  // provider.* + models.status (phase 8)
  ProviderListPayload,
  ProviderListResult,
  ProviderSetActivePayload,
  ProviderSetActiveResult,
  ProviderReloadPayload,
  ProviderReloadResult,
  ProviderRemovePayload,
  ProviderRemoveResult,
  ModelsStatusPayload,
  ModelsStatusResult,
  // telegram.* (phase 9)
  TelegramGetPayload,
  TelegramGetResult,
  TelegramSetEnabledPayload,
  TelegramSetEnabledResult,
  TelegramRestartPayload,
  TelegramRestartResult,
  TelegramSetTokenPayload,
  TelegramSetTokenResult,
  TelegramSetOwnerPayload,
  TelegramSetOwnerResult,
  TelegramPairPayload,
  TelegramPairResult,
  TelegramUnpairPayload,
  TelegramUnpairResult,
  // config.* (phase 10)
  ConfigGetPayload,
  ConfigGetResult,
  ConfigPatchPayload,
  ConfigPatchResult,
} from "./protocol/index.js";
